In [ ]:
#Question 1: Introduction of PyTorch Tensors and Basic Operations

import torch

# Check for Mac M4 GPU support
device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")
print(f"Using device: {device}")

# --- Part (a) Initialization & Data Types ---
print("\n--- (a) Initialization ---")
# Create a tensor from a list
t_data = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32, device=device)
# Create with random values
t_rand = torch.rand((2, 2), device=device)
# Create zeros
t_zeros = torch.zeros((2, 2), device=device)

print(f"Tensor from list:\n{t_data}")
print(f"Random Tensor:\n{t_rand}")

# --- Part (b) Operations ---
print("\n--- (b) Operations ---")
# Arithmetic
t_add = t_data + t_rand
t_mul = t_data * t_rand  # Element-wise multiplication
t_matmul = torch.matmul(t_data, t_rand) # Matrix multiplication

print(f"Addition:\n{t_add}")
print(f"Matrix Multiplication:\n{t_matmul}")

# Reshaping
t_flat = t_data.view(4) # Flatten to 1D
print(f"Reshaped (4,): {t_flat}")

# --- Part (c) Autograd ---
print("\n--- (c) Autograd ---")
# Create a tensor that requires gradient calculation
x = torch.tensor(2.0, requires_grad=True, device=device)
y = x ** 3 + 5  # Function: y = x^3 + 5

# Backward pass to calculate gradient (dy/dx = 3x^2)
y.backward()

print(f"x: {x.item()}")
print(f"y: {y.item()}")
print(f"Gradient (dy/dx at x=2): {x.grad.item()}") # Should be 3*(2)^2 = 12

Using device: mps

--- (a) Initialization ---
Tensor from list:
tensor([[1., 2.],
        [3., 4.]], device='mps:0')
Random Tensor:
tensor([[0.4578, 0.9106],
        [0.5090, 0.1133]], device='mps:0')

--- (b) Operations ---
Addition:
tensor([[1.4578, 2.9106],
        [3.5090, 4.1133]], device='mps:0')
Matrix Multiplication:
tensor([[1.4758, 1.1372],
        [3.4095, 3.1851]], device='mps:0')
Reshaped (4,): tensor([1., 2., 3., 4.], device='mps:0')

--- (c) Autograd ---
x: 2.0
y: 13.0
Gradient (dy/dx at x=2): 12.0


In [1]:
%pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [2]:
#Question 2: Perform all Linear Algebra operations with TensorFlow

import tensorflow as tf
import os

# Suppress TensorFlow logs
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

print("--- TensorFlow Linear Algebra ---")

# Define two matrices
A = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
B = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)

print(f"Matrix A:\n{A.numpy()}")
print(f"Matrix B:\n{B.numpy()}")

# 1. Matrix Multiplication
matmul = tf.matmul(A, B)
print(f"\nMatrix Multiplication (A x B):\n{matmul.numpy()}")

# 2. Transpose
transpose = tf.transpose(A)
print(f"\nTranspose of A:\n{transpose.numpy()}")

# 3. Determinant
det = tf.linalg.det(A)
print(f"\nDeterminant of A: {det.numpy()}")

# 4. Inverse
inv = tf.linalg.inv(A)
print(f"\nInverse of A:\n{inv.numpy()}")

# 5. Element-wise operations
add = tf.add(A, B)
print(f"\nElement-wise Addition:\n{add.numpy()}")

2026-01-16 08:44:22.512693: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1768553062.769346      55 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1768553062.845198      55 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1768553063.467525      55 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768553063.467581      55 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1768553063.467584      55 computation_placer.cc:177] computation placer alr

--- TensorFlow Linear Algebra ---
Matrix A:
[[1. 2.]
 [3. 4.]]
Matrix B:
[[5. 6.]
 [7. 8.]]

Matrix Multiplication (A x B):
[[19. 22.]
 [43. 50.]]

Transpose of A:
[[1. 3.]
 [2. 4.]]

Determinant of A: -2.0

Inverse of A:
[[-2.0000002   1.0000001 ]
 [ 1.5000001  -0.50000006]]

Element-wise Addition:
[[ 6.  8.]
 [10. 12.]]


2026-01-16 08:44:39.591059: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


In [3]:
#Question 3: Implement AND & OR Gates using Perceptron
import numpy as np

class Perceptron:
    def __init__(self, input_size, learning_rate=0.1, epochs=100):
        self.weights = np.zeros(input_size + 1) # +1 for bias
        self.lr = learning_rate
        self.epochs = epochs

    def activation(self, x):
        return 1 if x >= 0 else 0

    def predict(self, x):
        # z = w1*x1 + w2*x2 + ... + bias
        z = np.dot(x, self.weights[1:]) + self.weights[0]
        return self.activation(z)

    def train(self, X, y):
        for _ in range(self.epochs):
            for inputs, label in zip(X, y):
                prediction = self.predict(inputs)
                # Weight update rule: w = w + lr * (target - pred) * input
                self.weights[1:] += self.lr * (label - prediction) * inputs
                self.weights[0] += self.lr * (label - prediction)

# Data for AND Gate
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y_and = np.array([0, 0, 0, 1])

# Data for OR Gate
y_or = np.array([0, 1, 1, 1])

# --- Train AND Gate ---
p_and = Perceptron(input_size=2)
p_and.train(X, y_and)
print("\n--- AND Gate Predictions ---")
for x in X:
    print(f"{x} -> {p_and.predict(x)}")

# --- Train OR Gate ---
p_or = Perceptron(input_size=2)
p_or.train(X, y_or)
print("\n--- OR Gate Predictions ---")
for x in X:
    print(f"{x} -> {p_or.predict(x)}")


--- AND Gate Predictions ---
[0 0] -> 0
[0 1] -> 0
[1 0] -> 0
[1 1] -> 1

--- OR Gate Predictions ---
[0 0] -> 0
[0 1] -> 1
[1 0] -> 1
[1 1] -> 1


In [4]:
#Question 4: Implementation of XOR Problem using PyTorch Neural Network
import torch
import torch.nn as nn
import torch.optim as optim

device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")

# XOR Data (Inputs and Targets)
X = torch.tensor([[0,0], [0,1], [1,0], [1,1]], dtype=torch.float32).to(device)
y = torch.tensor([[0], [1], [1], [0]], dtype=torch.float32).to(device)

# Define Neural Network
class XORNet(nn.Module):
    def __init__(self):
        super(XORNet, self).__init__()
        self.hidden = nn.Linear(2, 4) # Input: 2 -> Hidden: 4
        self.output = nn.Linear(4, 1) # Hidden: 4 -> Output: 1
        self.relu = nn.ReLU()
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = self.relu(self.hidden(x))
        x = self.sigmoid(self.output(x))
        return x

model = XORNet().to(device)
criterion = nn.BCELoss() # Binary Cross Entropy Loss
optimizer = optim.SGD(model.parameters(), lr=0.1)

# Training
for epoch in range(5000):
    optimizer.zero_grad()
    outputs = model(X)
    loss = criterion(outputs, y)
    loss.backward()
    optimizer.step()

# Testing
print("\n--- XOR Problem Predictions ---")
with torch.no_grad():
    preds = model(X)
    print(preds.cpu().round()) # Move to CPU to print, round to 0 or 1


--- XOR Problem Predictions ---
tensor([[0.],
        [1.],
        [1.],
        [0.]])


In [5]:
#Question 5: Implement Simple Neural Network to solve Regression Problem
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")

# 1. Load Data
filename = 'house_price_full+(2) - house_price_full+(2).csv'
data = pd.read_csv(filename)
X = data[['bedrooms', 'sqft_living']].values
y = data['price'].values.reshape(-1, 1)

# 2. Preprocessing
scaler_x = StandardScaler()
scaler_y = StandardScaler()
X_scaled = scaler_x.fit_transform(X)
y_scaled = scaler_y.fit_transform(y)

X_tensor = torch.tensor(X_scaled, dtype=torch.float32).to(device)
y_tensor = torch.tensor(y_scaled, dtype=torch.float32).to(device)

# 3. Define Simple Regression Model (Matches the diagram structure concept)
class RegressionNet(nn.Module):
    def __init__(self):
        super(RegressionNet, self).__init__()
        # Assuming the diagram in PDF shows: Inputs -> Hidden -> Output
        self.layer1 = nn.Linear(2, 4)  # 2 Inputs (bedrooms, sqft)
        self.layer2 = nn.Linear(4, 1)  # 1 Output (price)
    
    def forward(self, x):
        x = torch.relu(self.layer1(x))
        x = self.layer2(x)
        return x

model = RegressionNet().to(device)
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

# 4. Training
epochs = 1000
for epoch in range(epochs):
    outputs = model(X_tensor)
    loss = criterion(outputs, y_tensor)
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    if (epoch+1) % 200 == 0:
        print(f'Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}')

# 5. Prediction Test
print("\n--- Regression Prediction ---")
# Test: 3 bedrooms, 2000 sqft
sample = scaler_x.transform([[3, 2000]])
sample_tensor = torch.tensor(sample, dtype=torch.float32).to(device)

with torch.no_grad():
    prediction_scaled = model(sample_tensor)
    prediction = scaler_y.inverse_transform(prediction_scaled.cpu().numpy())

print(f"Predicted Price for 3 Bed / 2000 Sqft: ${prediction[0][0]:,.2f}")

Epoch [200/1000], Loss: 0.5073
Epoch [400/1000], Loss: 0.5010
Epoch [600/1000], Loss: 0.4981
Epoch [800/1000], Loss: 0.4962
Epoch [1000/1000], Loss: 0.4946

--- Regression Prediction ---
Predicted Price for 3 Bed / 2000 Sqft: $496,653.75
